from typing import Protocol

from error_types import *

from result import *


class PasswordActions(Protocol):
    def reset_password(
        self, identity_id: str, password: str
    ) -> Result[IdentityNotExistsError, None]: ...

    def create_recovery_code(self, identity_id: str) -> Result[ClientRequestError, None]: ...

    def set_event_results(self, result: dict) -> None: ...

    def password_change_success(self) -> None: ...
    def password_recovery_success(self) -> None: ...

    def secret_not_found_fail(self) -> None: ...
    def juju_secret_not_found_fail(self) -> None: ...
    def model_error_while_fetch(self) -> None: ...
    def identity_fetch_error(self, e: Exception) -> None: ...
    def identity_does_not_exist(self, identity_id: str) -> None: ...
    def failed_kratos_api(self) -> None: ...

