[tox]
skipsdist = True
envlist = lint, static, unit

[vars]
src = {toxinidir}/src
tst = {toxinidir}/tests
uv  = uv run --frozen --isolated --extra=dev

[testenv]
allowlist_externals = uv
setenv =
  PYTHONPATH = {toxinidir}:{[vars]src}
  PY_COLORS = 1

[testenv:lock]
commands = uv lock --upgrade --no-cache

[testenv:fmt]
commands = {[vars]uv} ruff check --fix-only {[vars]src} {[vars]tst}

[testenv:lint]
commands = {[vars]uv} ruff check {[vars]src} {[vars]tst}

[testenv:static]
commands = {[vars]uv} pyright {[vars]src} {[vars]tst}

[testenv:unit]
setenv =
  {[testenv]setenv}
  JUJU_VERSION = 3.0.3
commands =
  {[vars]uv} coverage run --source={[vars]src} -m pytest {[vars]tst}/unit {posargs}
  {[vars]uv} coverage report
