from typing import Mapping, Protocol

from error_types import *
from ops.pebble import Layer

from result import *


class StatusActions(Protocol):
    def set_active(self) -> None: ...

    def set_maintenance(self) -> None: ...

    def set_failed_config_gen(self, e: Exception) -> None: ...

    def set_failed_config_push(self, e: Exception) -> None: ...

    def set_failed_update_service(self, e: Exception) -> None: ...

    def set_failed_replan(self, e: Exception, layer: Layer) -> None: ...

    def set_failed_config_reload(self) -> None: ...


class ConfigActions(Protocol):
    @property
    def status_actions(self) -> StatusActions: ...

    def push_prometheus_config(
        self, prometheus_config: Mapping
    ) -> Result[ConfigPushError, None]: ...

    def push_hash(self, hash: str) -> Result[ConfigPushError, None]: ...

    def reload_config(self) -> Result[ReloadError, None]: ...

    def update_layer(self, layer: Layer) -> Result[ServiceUpdateError, None]: ...

    def container_replan(self, layer: Layer) -> Result[ReplanError, None]: ...
